spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/payments?useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true

aws:
  sqs:
    endpoint: https://sqs.us-east-1.amazonaws.com
  region: us-east-1

queue:
    url: https://sqs.us-east-1.amazonaws.com/SEU-ID/payment-events

