
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/payments?connectTimeout=20000&socketTimeout=20000&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

aws:
  sqs:
    endpoint: http://localstack:4566
    queue-name: payment-events
    queue-url: http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/payment-events
  region: us-east-1
